### ISSUE TITLE
Userbot setup

### ISSUE THREAD

**Issue by sywork42** [OpenWeGrow/UserBot#1]
Hi,
I notice that there is no manual to setup the UserBot, so I made a rough guide (with help from the GroLab team) maybe it's not exactly perfect but it worked for me, if someone could review it and post it, I think it could be useful.
[Userbot_Setup.txt](https://github.com/OpenWeGrow/UserBot/files/2843330/Userbot_Setup.txt)

**Comment by OpenWeGrow** [comment]
This is right on spot, thanks for the contribution @sywork42!
We'll try to create an official document with this info.

Thanks for the support!

**Comment by OpenWeGrow** [comment]
Hi @sywork42,

Once again thank you for your contribution.

As promised we did the official instructions manual, available in English, Spanish, French, Portuguese, and Italian. We also hope the changes we did to the code also simplifies its usage.

The official GroLab UserBot manual [can be found here](https://opengrow.pt/downloads/manuals/grolab/userbot/UserBot-Shield-(EN-ES-FR-PT-IT)-2019V01.pdf).

Best regards,
Open Grow

**Comment by sywork42** [comment]
Whaou! Awesome,that's a very thorough manual! Thanks
Sy.

Sent from BlueMail<http://www.bluemail.me/r?b=15487>
On 26 Aug. 2019, at 23:33, Open Grow <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @sywork42<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsywork42&data=02%7C01%7C%7Cf5241aaba2e2415dfda008d72a3ab030%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637024303864829122&sdata=z22ATOJsu4FbOrzZdmoMCgPkzuFx962SWdxQqzceoS8%3D&reserved=0>,

Once again thank you for your contribution.

As promised we did the official instructions manual, available in English, Spanish, French, Portuguese, and Italian. We also hope the changes we did to the code also simplifies its usage.

The official GroLab UserBot manual can be found here<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fopengrow.pt%2Fdownloads%2Fmanuals%2Fgrolab%2Fuserbot%2FUserBot-Shield-(EN-ES-FR-PT-IT)-2019V01.pdf&data=02%7C01%7C%7Cf5241aaba2e2415dfda008d72a3ab030%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637024303864839131&sdata=%2B9X2ImQucuszMSwjIzlcKMM6EL2BdGonQGijG5RNmnc%3D&reserved=0>.

Best regards,
Open Grow
